### ISSUE TITLE
Add-on Wont start after update to v1.3.1

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#37]
Log File:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:15:48] INFO: Installed custom component.
[2023-07-07T17:15:49.058] [INFO] default - Whatsapp Addon started.
/whatsapp.js:51
        const { state, saveState } = useSingleFileAuthState(this.#path)
                                     ^

TypeError: useSingleFileAuthState is not a function
    at WhatsappClient.connect (/whatsapp.js:51:38)
    at new WhatsappClient (/whatsapp.js:45:14)
    at init (/index.js:97:18)
    at /index.js:111:5
    at Array.forEach (<anonymous>)
    at /index.js:110:19
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ekkesa** [comment]
v 1.3.2 resolved the issue. 

Thank you!
